version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn
      - run: yarn run lint
      - run: yarn run test  -- -t $CI_CODECOV_TOKEN
